version: "3.9"
networks:
  roboshop:
    driver: bridge
  volumes:
#this is equalent to docker volume create and these are named volumes
#anonymous volume, docker wont be having control
#docker run -v /home/ec2-user/mysql:/var/lib/mysql
#docker volumes create mysql (to this docker will have control to manage volumes)
    mysql:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/ec2-user/mysql
    redis:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/ec2-user/redis
    rabbitmq:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/ec2-user/rabbitmq
    mongodb:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/ec2-user/mongodb
services:
  web:
    image: web:v1
    build:
      context: 1-web/
    #   dockerfile: DockerFile
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping 
  mongodb:
    image: mongodb:v1
    build:
      context: 2-mongo/
    #   dockerfile: DockerFile
    container_name: mongodb
    volume:
    - mongodb:/data/db    
  catalogue:
    image: catalogue:v1
    build:
      context: 3-catalogue/
    #   dockerfile: DockerFile
    container_name: catalogue
    depends_on: 
    - mongodb

  redis:
    image: redis
    container_name: redis
    volume:
    - redis:/data

  user: 
    image: user:v1
    build:
      context: 5-user
    container_name: user
    depends_on:
    - mongodb
    - redis

  cart: 
    image: cart:v1
    build:
      context: 6-cart
    container_name: cart
    depends_on:
    - redis
    - catalogue

  mysql:
    image: mysql:v1
    build:
      context: 7-mysql
    container_name: mysql
    volume:
    - mysql:/var/lib/mysql

  shipping: 
    image: shipping:v1
    build:
      context: 8-shipping
    container_name: shipping
    depends_on:
    - mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volume:
    - rabbitmq:/var/lib/rabbitmq

  payment: 
    image: payment:v1
    build:
      context: 9-payment
    container_name: payment
    depends_on:
    - rabbitmq

  ratings: 
    image: ratings:v1
    build:
      context: 10-ratings
    container_name: ratings
    depends_on:
    - mysql
  




