version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: web:v1
    build:
      context: 1-web/
    #   dockerfile: DockerFile
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping 
  mongodb:
    image: mongodb:v1
    build:
      context: 2-mongo/
    #   dockerfile: DockerFile
    container_name: mongodb
    
  catalogue:
    image: catalogue:v1
    build:
      context: 3-catalogue/
    #   dockerfile: DockerFile
    container_name: catalogue
    depends_on: 
    - mongodb

  redis:
    image: redis

  user: 
    image: user:v1
    build:
      context: 5-user
    container_name: user
    depends_on:
    - mongodb
    - redis

  cart: 
    image: cart:v1
    build:
      context: 6-cart
    container_name: cart
    depends_on:
    - redis
    - catalogue

  mysql:
    image: mysql:v1
    build:
      context: 7-mysql
    container_name: mysql

  shipping: 
    image: shipping:v1
    build:
      context: 8-shipping
    container_name: shipping
    depends_on:
    - mysql

  payment: 
    image: payment:v1
    build:
      context: 9-payment
    container_name: payment
    depends_on:
    - rabbitmq

  ratings: 
    image: ratings:v1
    build:
      context: 10-ratings
    container_name: ratings
    depends_on:
    - mysql
  




