version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: web:v1
    build:
      context: 1-web/
    #   dockerfile: DockerFile
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    image: mongodb:v1
    build:
      context: 2-mongo/
    #   dockerfile: DockerFile
    container_name: mongodb
    
  catalogue:
    image: catalogue:v1
    build:
      context: 3-catalogue/
    #   dockerfile: DockerFile
    container_name: catalogue
    depends_on: 
    - mongodb

  redis:
    image: redis

  user: 
    image: user:v1
    build:
      context: 5-user
    container_name: user
    depends_on:
    - mongodb
    - redis



